name: ci

on:
  push:
    branches:
    - master
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Code Coverage
      run: |
        set -e
        apk add --no-cache git make || sudo apt-get install -y git make
        sudo -s /bin/sh -c 'make test' # Force make to run docker under root user
        bash <(curl -s https://codecov.io/bash)

  build-docker-image:
    needs: [test]
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64]
    name: build-docker-image
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v3
    - name: Login to docker registry
      run: echo "${DOCKERHUB_REGISTRY_PASSWORD}" | docker login -u "${DOCKERHUB_REGISTRY_USER}" --password-stdin
      env:
        DOCKERHUB_REGISTRY_USER: ${{ secrets.DOCKERHUB_REGISTRY_USER }}
        DOCKERHUB_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_REGISTRY_PASSWORD }}
    - name: Build and push image
      env:
        DOCKERHUB_REGISTRY_USER: ${{ secrets.DOCKERHUB_REGISTRY_USER }}
      run: |
        set -e
        make build-image push-image "GOOS=$GOOS" "GOARCH=$GOARCH" "REGISTRY_USER=$DOCKERHUB_REGISTRY_USER"
    - name: Clean-up
      run: docker logout
      if: always()

  update-draft-release:
    needs: [test, build-docker-image]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: [test, build-docker-image, update-draft-release]
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64]
    name: release
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        set -e
        make build "GOOS=$GOOS" "GOARCH=$GOARCH"
    # Drafts your next Release notes as Pull Requests are merged into "master"
    - name: create_release
      uses: release-drafter/release-drafter@v5
      with:
        config-name: release-drafter.yaml
        publish: true
        name: ${{  github.ref_name }}
        tag: ${{  github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: |
          ./.go/bin/*
